name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for artifact upload
    
    steps:
      # Checkout the repository (required for Platane/snk v2+)
      - uses: actions/checkout@v4
        
      # Generate the snake animation
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: "snake.svg"
          gif_out_path: "snake.gif"
        
      # Upload SVG artifact (updated to v4)
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: |
            snake.svg
            snake.gif
