name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      # Generate snake files in a specific directory
      - name: Create Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: akbarabay713
          svg_out_path: output/snake.svg  # Explicit output path
          gif_out_path: output/snake.gif   # In an 'output' folder
          
      # Verify files exist before upload
      - name: List files (debug)
        run: ls -R output/
        
      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: output/*
