name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      # Updated snake generation step
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: akbarabay713
          outputs: svg_path=snake.svg gif_path=snake.gif
        
      # Upload both files in one step
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: |
            snake.svg
            snake.gif
