name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      # Main snake generation step
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: akbarabay713
          outputs: |
            svg_path=snake.svg
            gif_path=snake.gif
          
      # Upload both files
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: |
            snake.svg
            snake.gif
